spring:
  application:
    name: auth-service
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server 
      fail-fast: true # If it can't find the Vault, it stops immediately (cleaner)
      retry:
        initial-interval: 1000
        max-interval: 2000 
        max-attempts: 6
  config:
    import: "optional:configserver:"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/